config/routes.rb
Rails.application.routes.draw do

  resources :loans

  resource :account_summary, only: [:show], controller: 'account_summary'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root to: 'account_summary#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/loan/stateful.rb
module Loan
  module Stateful
    extend ActiveSupport::Concern

    included do
      enum status: {
        requested: 0,
        rejected: 1,
        approved: 2,
        open: 3,
        closed: 4,
        waiting_for_adjustment_acceptance: 5,
        readjustment_requested: 6
      }

      # { from: [:to] }
      PERMITTED_STATUS_CHANGES ||= {
        requested: [:approved, :rejected, :waiting_for_adjustment_acceptance],
        approved: [:open],
        rejected: [],
        waiting_for_adjustment_acceptance: [:open, :rejected, :readjustment_requested],
        readjustment_requested: [:approved, :rejected, :waiting_for_adjustment_acceptance],
        open: [:closed],
        closed: []
      }

      # who is responsible
      ACTOR ||= {
        approved: [:admin],
        rejected: [:admin, :borrower],
        waiting_for_adjustment_acceptance: [:admin],
        readjustment_requested: [:borrower],
        open: [:borrower],
        closed: [:borrower, :admin]
      }
    end
  end
end

app/models/loan_account.rb
class LoanAccount < ApplicationRecord
  include Loan::Stateful

  belongs_to :borrower, class_name: 'User', foreign_key: 'borrower_id'
  belongs_to :editor, class_name: 'User', foreign_key: 'editor_id', optional: true
  has_many :loan_account_edit_histories

  before_validation :set_initial_status

  validates :amount, :interest_percentage, :status, presence: true
  validate :permitted_status_change, on: :update

  alias_attribute :interest, :interest_percentage

  attr_accessor :comment

  def values_changed?
    amount != amount_was || interest_percentage != interest_percentage_was
  end

  private

  def set_initial_status
    self.status ||= :requested
  end

  def permitted_status_change
    return if true || status == status_was || PERMITTED_STATUS_CHANGES[status_was.to_sym].include?(status.to_sym)

    errors.add(:status, 'not permitted')
  end
end

app/models/loan_account_edit_history.rb
class LoanAccountEditHistory < ApplicationRecord
  include Loan::Stateful

  belongs_to :loan_account
  belongs_to :editor, class_name: 'User', foreign_key: 'editor_id', optional: true

  validates :amount, :interest, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :wallet_account
  has_many :loan_accounts, foreign_key: :borrower_id

  validates :full_name, presence: true
end

app/models/wallet_account.rb
class WalletAccount < ApplicationRecord
  belongs_to :user
end

app/controllers/account_summary_controller.rb
class AccountSummaryController < ApplicationController
  def show
    @wallet = current_user.wallet_account
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit :sign_up, keys: [:full_name]
  end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, except: [:index, :new, :create]
  before_action :authorize_resource, except: [:index, :new, :create]
  before_action :set_loan_service, only: [:create, :update]

  def index
    @loans = LoanAccount.all
    @loans = @loans.where(status: params[:filter]) if params[:filter]
    @loans = @loans.where(borrower_id: current_user.id) unless current_user.admin?
    @loans = @loans.includes(:borrower).order(:status)
  end

  def show
    @loan = LoanPresenter.new(@loan, current_user)
  end

  def new
    @loan = LoanAccount.new
  end

  def create
    authorize @service.account

    @service.call

    set_controller_create_message

    @loan = @service.account
    if @service.account.errors.present?
      render :new
      return
    end

    redirect_to loan_path(@loan)
  end

  def edit; end

  def update
    @service.call

    set_controller_update_message

    @loan = @service.account
    if @service.account.errors.present?
      render :edit
      return
    end

    redirect_to loan_path(@loan)
  end

  private

  def set_loan
    @loan = LoanAccount.find(params[:id])
  end

  def set_loan_service
    @service = LoanService.new(
                                account: (action_name == 'create' ? LoanAccount.new : @loan) ,
                                action: params[:commit].parameterize(separator: '_'),
                                actor: current_user,
                                params: loan_params
                              )
  end

  def set_controller_update_message
    if @service.errors.present?
      flash[:alert] = @service.account.errors.present? ? @service.errors : 'Something went wrong'
    else
      flash[:notice] = "Status changed to #{@service.account.status}"
    end
  end

  def set_controller_create_message
    if @service.errors.present?
      flash[:alert] = @service.account.errors.present? ? @service.errors : 'Something went wrong'
    else
      flash[:notice] = "Loan created and requested"
    end
  end

  def loan_params
    return {} unless params[:loan_account].present?

    if action_name == 'update'
      params.require(:loan_account).permit(:amount, :interest_percentage, :comment)
    else
      params.require(:loan_account).permit(:amount, :interest_percentage)
    end
  end

  def authorize_resource
    authorize @loan
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  def create
    user_generator = UserGenerator.new(sign_up_params)
    user_generator.generate
    @user = user_generator.user

    if @user.persisted?
      sign_up(resource_name, @user)
      respond_with @user, location: after_sign_up_path_for(@user)
    else
      clean_up_passwords(@user)
      set_minimum_password_length
      respond_with @user
    end
  end

  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :full_name)
  end
end

app/helpers/account_summary_helper.rb
module AccountSummaryHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/account_summary/show.html.erb
<div class="account-summary">
  <h2>Account Summary</h2>
  <hr/>
  <div class="card mt-5">
    <div class="card-body">
      <p class="card-text text-muted small mb-0">Balance</p>
      <h1 class="card-title">$<%= @wallet.balance %></h1>
    </div>
    <div class="card-footer text-muted">
      <p><strong>Account Holder: </strong> <%= current_user.full_name %></p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id="wrapper" class="d-flex">
      <% if user_signed_in? %>
      <div id="sidebar-wrapper" class="border-end bg-white">
          <div class="sidebar-heading border-bottom bg-light">Wallet-App</div>
          <div class="list-group list-group-flush">
              <%= link_to 'Account Summary', account_summary_path, class: 'list-group-item list-group-item-action list-group-item-light p-3' %>
              <%= link_to "Loans",
                loans_path,
                class: 'list-group-item list-group-item-action list-group-item-light p-3' %>
            <%= link_to "Logout", destroy_user_session_path, class: 'text-danger list-group-item list-group-item-action list-group-item-light p-3' %>
          </div>
      </div>
      <% end %>
      <div id="page-content-wrapper">
        <% if notice %>
          <div class="alert alert-warning m-3" role="alert">
            <%= notice %>
          </div>
        <% end %>
        <% if alert %>
          <div class="alert alert-danger m-3" role="alert">
            <%= alert %>
          </div>
        <% end %>
        <div class="container-fluid p-5">
            <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/loans/_actions.html.erb
<%= form_with(model: loan, local: true, html: { data: { turbo: false } }, url: loan_path(loan)) do |form| %>
  <% actions.each do |action| %>
    <% if action[:method] == :get %>
      <%= link_to action[:name].titleize, action[:path], class: "m-1 btn #{action[:class]}" %>
    <% else %>
      <%= form.submit action[:name].titleize, class: "m-1 btn #{action[:class]}", name: "commit", value: action[:name].titleize %>
    <% end %>
  <% end %>
<% end %>

app/views/loans/_form.html.erb
<%= form_with(model: loan, local: true, html: { class: 'form-horizontal', data: { turbo: false } }, url:) do |form| %>
  <div class="form-group m-2">
    <%= form.label :amount, class: 'control-label' %>
    <%= form.text_field :amount, class: 'form-control' %>
  </div>

  <div class="form-group m-2">
    <%= form.label :interest, class: 'control-label' %>
    <%= form.text_field :interest_percentage, class: 'form-control' %>
  </div>


  <% if enable_comment %>
    <div class="form-group m-2">
      <%= form.label :comment, class: 'control-label' %>
      <%= form.text_area :comment, class: 'form-control' %>
    </div>
  <% end %>

  <div class="form-group m-2">
    <%= form.submit (loan.id ? 'Update' : 'Create'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/loans/_info.html.erb
<p class="d-flex">
  <strong class="mb-2 text-muted">Repay Amount</strong>
  <div class="d-flex align-items-baseline">
    <h1>$<%= loan.repay_amount || loan.amount %></h1> &nbsp;
    <% if false %>
      <span>for <strong><%= loan.interest %>%</strong></span>
    <% end %>
  </div>
</p>

app/views/loans/edit.html.erb
<div class="edit-loan">
  <h2>Loans</h2>
  <hr/>
  <div class="card mt-5">
    <div class="card-body p-3">
      <%= render 'loans/form', loan: @loan, url: loan_path(@loan), enable_comment: true %>
    </div>
  </div>
</div>

app/views/loans/index.html.erb
<div class="loans">
  <div class="d-flex justify-content-between">
    <% if !current_user.admin? %>
      <h2>Loans</h2>
      <span>
        <%= link_to 'New Loan', new_loan_path, class: "btn btn-success" %>
      </span>
    <% end %>
  </div>
  <hr/>
  <div class="card mt-5">
    <div class="card-body p-3">
      <div>
        <%= link_to 'ALL', loans_path, class: "btn btn-outline-primary #{'active' unless params[:filter]}" %>
        <% LoanAccount.statuses.keys.each do |status| %>
          <%= link_to status.titleize, loans_path(filter: status), class: "btn btn-outline-primary #{'active' if params[:filter] == status}" %>
        <% end %>
      </div>

      <div class="mt-5">
        <% if @loans.empty? %>
          No loans found
        <% else %>
          <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col">Date and Time</th>
                <th scope="col">Status</th>
                <% if current_user.admin? %>
                  <th>Requested By</th>
                <% end %>
                <th>Requested Amount</th>
                <th>Current Amount</th>
              </tr>
            </thead>
            <tbody>
              <% @loans.each do |loan| %>
                <% presenter = LoanPresenter.new(loan) %>
                <tr>
                  <td>
                    <%= link_to presenter.created_at, loan_path(loan), class: 'text-decoration-none' %>
                  </td>
                  <td scope="row"><%= presenter.status %></td>
                  <% if current_user.admin? %>
                    <td scope="row"><%= presenter.requested_by %></td>
                  <% end %>
                  <td scope="row"><%= presenter.amount %></td>
                  <td scope="row"><%= presenter.repay_amount || '-' %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/loans/new.html.erb
<div class="new-loan">
  <h2>Loans</h2>
  <hr/>
  <div class="card mt-5">
    <div class="card-body p-3">
      <%= render 'loans/form', loan: @loan, url: loans_path, enable_comment: false %>
    </div>
  </div>
</div>

app/views/loans/show.html.erb
<div class="loan">
  <h2>Loans</h2>
  <hr/>
  <div class="card mt-5">
    <div class="card-body">
      <%= render 'loans/info', loan: @loan %>
    </div>
    <div class="card-footer text-muted pb-3">
      <% if current_user.admin? %>
        <p class="mt-3"><strong>Requested By</strong> <br/>
          <%= @loan.requested_by %>
        </p>
      <% end %>

      <p class="mt-3"><strong>Requested / Edited Amount</strong> <br/>
        <%= @loan.amount %> for <%=@loan.interest %>%
      </p>

      <p class="mt-3"><strong>Status</strong> <br/>
        <%= @loan.status.titleize %>
      </p>

      <p class="mt-3 mb-2"><strong>Actions</strong></p>
      <% if @loan.actions.empty? %>
          <span><%= @loan.status.titleize %></span>
      <% end %>
      <div class="d-inline-flex">
        <%= render 'loans/actions', actions: @loan.actions, loan: @loan.record %>
      </div>
    </div>
  </div>
  <div>
    <div class="card mt-5">
      <div class="card-body">
        <h3>History</h3>
        <div class="mt-5">
          <% if @loan.history.present? %>
            <table class="table table-striped">
              <thead>
                <tr>
                  <th scope="col">Amount</th>
                  <th scope="col">Interest</th>
                  <th scope="col">Change</th>
                </tr>
              </thead>
              <tbody>
                <% @loan.history.each.with_index do |edit, index| %>
                  <tr>
                    <td scope="row"><%= edit.amount %></td>
                    <td scope="row"><%= edit.interest %></td>
                    <td scope="row"><%= edit.status.titleize %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <% else %>
                  <p> Nothing yet.</p>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>